In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class MyModel(nn.Module):
  def __init__(self, in_dim, out_dim):
    super().__init__()
    self.linear = nn.Linear(in_dim, out_dim)

  def forward(self, x):
    return self.linear(x)

model = MyModel(1, 1)

In [3]:
x = torch.tensor([[1.], [2.], [3.], [4.], [5.], [6.], [7.], [8.], [9.]], requires_grad=True)
y = torch.tensor([[11.], [22.], [33.], [44.], [53.], [66.], [77.], [87.], [95.]], requires_grad=True)

In [6]:
learning_rate = 0.01
nb_epochs = 300
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
loss_func = nn.MSELoss()

In [7]:
for i in range(nb_epochs):
  pred = model(x)
  loss = loss_func(pred, y)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()


In [9]:
print(loss)
for param in model.parameters():
    print (param)

tensor(1.0630, grad_fn=<MseLossBackward0>)
Parameter containing:
tensor([[10.6642]], requires_grad=True)
Parameter containing:
tensor([0.9262], requires_grad=True)


In [11]:
print(model(torch.tensor([8.5,])))

tensor([91.5716], grad_fn=<AddBackward0>)
